/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;
import Services.MahasiswaService;
import Objects.Mahasiswa;
import Util.SecurityUtils;
import Util.EncryptionUtils;
import javax.swing.JOptionPane;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoCollection;
import org.bson.Document;
import Util.MongoManager;

/**
 *
 * @author ADVAN
 */
public class AttendancePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AttendancePage.class.getName());

    /**
     * Creates new form AttendancePage
     */
    public AttendancePage() {
        initComponents(); // Kode bawaan NetBeans untuk inisialisasi komponen GUI
        
        // --- KODE REAL-TIME UNTUK TANGGAL DAN JAM ---
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mengambil waktu saat ini
                Date waktuSekarang = new Date();
                
                // Format Tanggal: Kamis, 18 Juni 2026 (menggunakan bahasa Indonesia)
                SimpleDateFormat formatTanggal = new SimpleDateFormat("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
                
                // Format Jam: HH:mm:ss (Jam:Menit:Detik)
                SimpleDateFormat formatJam = new SimpleDateFormat("HH:mm:ss");
                
                // Terapkan hasil format ke masing-masing label
                lbltgl.setText(formatTanggal.format(waktuSekarang));
                lbljam.setText(formatJam.format(waktuSekarang));
            }
        });
        
        // Menjalankan timer
        timer.start();
        // --------------------------------------------
        
        clearForm();
    }

    /**
     * Helper method untuk mengosongkan form kembali setelah digunakan
     */
private void clearForm() {
        lbluid.setText(""); // Bersihkan input UID
        
        // --- RESET TOTAL TAMPILAN TENGAH ---
        lblstatus.setText("");
        lblnamabsr.setText("");
        lblnim.setText("");
        lblkelas.setText("");
        lblicon.setVisible(false);
        masuk.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbltgl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbljam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        masuk = new javax.swing.JButton();
        lbluid = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        lblnamabsr = new javax.swing.JLabel();
        lblnim = new javax.swing.JLabel();
        lblkelas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        lbltgl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltgl.setForeground(new java.awt.Color(255, 255, 255));
        lbltgl.setText("tanggal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltgl, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lbltgl)
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        lbljam.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbljam.setForeground(new java.awt.Color(255, 255, 255));
        lbljam.setText("waktu");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEKARANG");

        masuk.setText("Masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });

        lbluid.setText("UID");
        lbluid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbluidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbljam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbluid)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbluid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/masuk.png"))); // NOI18N

        lblstatus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(51, 204, 0));
        lblstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstatus.setText("jLabel3");

        lblnamabsr.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblnamabsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnamabsr.setText("jLabel4");

        lblnim.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblnim.setForeground(new java.awt.Color(51, 204, 0));
        lblnim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnim.setText("jLabel3");

        lblkelas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblkelas.setForeground(new java.awt.Color(51, 204, 0));
        lblkelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblkelas.setText("jLabel3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblnamabsr, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(lblstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblkelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblicon)
                        .addGap(241, 241, 241))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblicon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblkelas)
                .addGap(18, 18, 18)
                .addComponent(lblnamabsr)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        String namaMhs = lblnamabsr.getText().trim();
        String nimMhs = lblnim.getText().trim();
        String kelasMhs = lblkelas.getText().replace("Kelas: ", "").trim();

        // Validasi apakah form masih kosong (belum tap kartu)
        if (nimMhs.isEmpty() || namaMhs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan tap kartu RFID terlebih dahulu!", "Peringatan SEMAWA", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Menangkap waktu penekanan tombol log absen
            Date sekarang = new Date();
            SimpleDateFormat formatTanggal = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat formatJam = new SimpleDateFormat("HH:mm:ss");
            
            String tanggalAbsen = formatTanggal.format(sekarang);
            String jamAbsen = formatJam.format(sekarang);

            // 1. UPDATE PANEL TENGAH MENJADI NOTIFIKASI BERHASIL MASUK
            lblstatus.setText("Sukses Hadir! (" + jamAbsen + ")");
            // Nama, NIM, dan Kelas tetap dibiarkan tampil di panel tengah agar terbaca oleh user

            // 2. SIMPAN LOG ABSENSI KE MONGODB
            MongoDatabase database = MongoManager.getDatabase();
            MongoCollection<Document> collection = database.getCollection("Absensi_log");

            // Membuat struktur document data (NIM asli disimpan sebagai teks biasa)
            Document logAbsen = new Document()
                    .append("nim", nimMhs)
                    .append("nama", namaMhs)
                    .append("kelas", kelasMhs)
                    .append("tanggal", tanggalAbsen)
                    .append("jam", jamAbsen);

            // Eksekusi simpan data ke MongoDB
            collection.insertOne(logAbsen);
            
            // 3. JEDA 3 DETIK SEBELUM FORM RESET OTOMATIS
            Timer delayReset = new Timer(3000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    clearForm(); 
                    lbluid.requestFocus(); // Kembalikan fokus ke kolom UID untuk tap selanjutnya
                }
            });
            
            delayReset.setRepeats(false); 
            delayReset.start(); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencatat kehadiran ke Database: " + e.getMessage(), "Error SEMAWA", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_masukActionPerformed

    private void lbluidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbluidActionPerformed
                                     
        // Mengambil teks, menghapus spasi di awal/akhir, dan memaksanya menjadi huruf kecil
        String uidMentah = lbluid.getText().trim().toLowerCase(); 
        
        if (!uidMentah.isEmpty()) {
            try {
                MahasiswaService service = new MahasiswaService();
                
                // Melakukan proses hash dari teks yang sudah dibersihkan
                String uidHashed = SecurityUtils.getHash(uidMentah, SecurityUtils.SHA_256);
                
                System.out.println("UID Mentah di-input: " + uidMentah);
System.out.println("Hasil Hash komputer kamu: " + uidHashed);
                
                // Tambahan proteksi: pastikan string hash hasil generate juga dipaksa huruf kecil
                uidHashed = uidHashed.trim().toLowerCase();
                
                // Cari data ke MongoDB lewat MahasiswaService
                Mahasiswa mhs = service.findByUid(uidHashed); 
                
                if (mhs != null) {
                    // Dekripsi NIM asli dari database untuk ditampilkan di SEMAWA
                    String nimAsli = EncryptionUtils.decrypt(mhs.getNimMahasiswa());
                    
                    // 1. TAMPILKAN DATA KE PANEL TENGAH
                    lblstatus.setText("Data Kartu Ditemukan:");
                    lblnamabsr.setText(mhs.getNamaLengkap());
                    lblnim.setText(nimAsli);
                    lblkelas.setText("Kelas: " + mhs.getKelas());
                    lblicon.setVisible(true); 
                    
                    // 2. OTOMATISASI: LANGSUNG ABSEN TANPA KLIK TOMBOL
                    masukActionPerformed(null);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Kartu tidak terdaftar!", "Error SEMAWA", JOptionPane.ERROR_MESSAGE);
                    clearForm();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal membaca kartu: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                clearForm();
            }
        }
    }//GEN-LAST:event_lbluidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AttendancePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lbljam;
    private javax.swing.JLabel lblkelas;
    private javax.swing.JLabel lblnamabsr;
    private javax.swing.JLabel lblnim;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JTextField lbluid;
    private javax.swing.JButton masuk;
    // End of variables declaration//GEN-END:variables
}
